global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:3000']  # adjust to your app container name and port
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']